# Generated by Django 3.2.5 on 2024-08-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_auto_20240813_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('month', models.IntegerField(default=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField(blank=True)),
                ('salary_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.salaryscale')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
            options={
                'ordering': ['-year', '-month', 'staff'],
                'unique_together': {('staff', 'year', 'month')},
            },
        ),
    ]
