# Generated by Django 3.2.5 on 2024-08-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_monthlysalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='salary_scale',
        ),
    ]
