# Generated by Django 3.2.5 on 2024-08-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('staffs', '0006_alter_monthlysalary_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlysalary',
            options={'ordering': ['-session', '-year', '-month', 'staff']},
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession'),
        ),
    ]
