# Generated by Django 3.2.5 on 2025-03-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_auto_20240814_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
