# Generated by Django 3.2.5 on 2025-03-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20250318_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Cost'), ('INSURANCE', 'Vehicle Insurance'), ('SALARY', 'Staff Salary'), ('PERMIT', 'Vehicle Permits/Licenses'), ('PARTS', 'Spare Parts'), ('TOOLS', 'Tools and Equipment'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('paid_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Leave blank if expense is not vehicle-specific', null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Routine Service'), ('REPAIR', 'Repair Work'), ('INSPECTION', 'Vehicle Inspection'), ('TIRE', 'Tire Service'), ('OTHER', 'Other Maintenance')], max_length=20)),
                ('mechanic_name', models.CharField(max_length=100)),
                ('mechanic_contact', models.CharField(blank=True, max_length=100)),
                ('workshop_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('odometer_reading', models.PositiveIntegerField(help_text='Vehicle mileage at service time')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transport.vehicle')),
            ],
        ),
    ]
