# Generated by Django 3.2.5 on 2025-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_maintenancerecord_transportexpenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
