# Generated by Django 3.2.5 on 2025-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttransportassignment',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
    ]
