# Generated by Django 3.2.5 on 2025-03-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20250320_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttransportassignment',
            options={'ordering': ['route', 'student']},
        ),
        migrations.RemoveField(
            model_name='studenttransportassignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studenttransportassignment',
            name='transport_fee',
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='studenttransportassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='unique_active_student_assignment'),
        ),
    ]
