# Generated by Django 3.2.5 on 2025-03-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20250320_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
    ]
