# Generated by Django 3.2.5 on 2025-03-20 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_studenttransportassignment_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportexpenditure',
            options={'ordering': ['-date', '-expenditure_number'], 'verbose_name': 'Transport Expenditure', 'verbose_name_plural': 'Transport Expenditures'},
        ),
        migrations.AddField(
            model_name='transportexpenditure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transportexpenditure',
            name='expenditure_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transportexpenditure',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
